# Generated by Django 4.1.7 on 2023-03-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=255)),
                ('probability', models.CharField(max_length=255)),
            ],
        ),
    ]
